on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: code-quality-check
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -yq libgl1-mesa-dev xorg-dev
      - name: Clone repo
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
