on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: code-quality-check
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y libgl1-mesa-dev xorg-dev
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
